$(function(){
    var h5 = new H5();

   /* h5.whenAddPage = function(){
        this.addComponent('slide_up',{
            bg:'imgs/footer.png',
            css:{
                opacity:0,
                left:0,bottom:-20,
                width:'100%',height:'20px',zIndex:999
            },
            animateIn:{
                opacity:1,bottom:'-1px'
            },
            animateOut:{
                opacity:0,bottom:'-20px'
            },
            delay:500
        });
    };*/

    h5
        .addPage('face')
            .addComponent('logo',{
            center:true,
            width:395,
            height:130,
            bg:'imgs/logo.png',
            css:{opacity:0},
            animateIn:{top:100,opacity:1},
            animateOut:{top:0,opacity:0},
        })
            .addComponent('face_img_left',{
            width:370,
            height:493,
            bg:'imgs/face_img_left.png',
            css:{opacity:0,left:-50,bottom:-50},
            animateIn:{opacity:1,left:0,bottom:0},
            animateOut:{opacity:0,left:-50,bottom:-50},
            delay:1000
        })
            .addComponent('face_img_right',{
            width:276,
            height:449,
            bg:'imgs/face_img_right.png',
            css:{opacity:0,right:-50,bottom:-50},
            animateIn:{opacity:1,right:0,bottom:0},
            animateOut:{opacity:0,right:-50,bottom:-50},
            delay:1000
        })
            .addComponent('slogan',{
            //center:true,
            width:160,
            height:160,
            bg:'imgs/icebear1.png',
            css:{opacity:0,top:'30%',
                left:'35%',marginLeft:'-40px'
            },
            animateIn:{opacity:1},
            animateOut:{opacity:0},
            delay:500
        })
            .addComponent('slogan yang',{
            //center:true,
            fontFamily:'华文细黑',
            width:300,
            height:160,
            text:'杨小事er',
            css:{opacity:0,top:'30%',
                fontSize:'25px',
                paddingTop:'30px',
                color:'#fff',
                left:'70%',
                marginLeft:'-75px'
            },
            animateIn:{opacity:1},
            animateOut:{opacity:0},
            delay:500
        })
        .addPage()
            .addComponent('caption',{text:'这是个标题'})
            .addComponent('text_big',{
            width:500,
            height:30,
            center:true,
            text:'对，这就是一个广告!',
            css:{
                opacity:0,textAlign:'center',color:'#5D5D5D',fontSize:'26px', fontWeight:'700',
                fontFamily:'Tahoma,Arial,”Helvetica Neue“,”Hiragino Sans GB”,Simsun,sans-self'
            },
            animateIn:{opacity:1,top:120},
            animateOut:{opacity:0,top:240},
        })
            .addComponent('description',{
            center:true,
            width:481,
            height:295,
            bg:'imgs/description_bg.png',
            css:{
                opacity:0,
                padding:'20px 10px 10px 10px',
                color:'#000',
                fontSize:'18px',
                lineHeight:'20px',
                textAlign:'justify',
                top:240
            },
            text:['想让你的简历脱颖而出？想拥有一份在线简历？或者想做一份H5的摄影约片广告？' +
            '或者想交给boss一份在线观看的数据报表？'],
            animateIn:{opacity:1,top:190},
            animateOut:{opacity:0,top:240},
            delay:1000
        })
            .addComponent('people',{
            center:true,
            width:515,
            height:305,
            bg:'imgs/p1_people.png',
            css:{
                opacity:0,
                bottom:0
            },
            animateIn:{opacity:1,bottom:40},
            animateOut:{opacity:0,bottom:0},
            delay:500
        })
        .addPage()
            .addComponent('caption',{text:'这是个标题'})
        .addPage('tail')
            .addComponent('logo',{
            center:true,
            width:191,
            height:194,
            bg:'imgs/twoweima.jpg',
            css:{top:220,opacity:0},
            animateIn:{opacity:1,top:210},
            animateOut:{opacity:0,top:240},
        })
            .addComponent('slogan',{
            center:true,
            width:314,
            height:46,
            bg:'imgs/tail_slogan.png',
            css:{top:320,opacity:0},
            animateIn:{opacity:1,left:'50%'},
            animateOut:{opacity:0,left:'0%'},
            delay:500
        })
            .addComponent('share',{
                width:128,
                height:120,
                bg:'imgs/tail_share.png',
                css:{opacity:0,top:110,right:110},
                animateIn:{opacity:1,top:10,right:10},
                animateOut:{opacity:0,top:110,right:110},
                delay:1000
            })
            .addComponent('back',{
            width:52,
            height:50,
            bg:'imgs/tail_back.png',
            center:true,
            onclick : function(){
                $.fn.fullpage.moveTo( 1 )
            }
        })
        .loader(4);
});